## Indexing

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("files/world_population.csv")

In [4]:
df.set_index("Country", inplace=True)

In [11]:
df.head()

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00

In [6]:
df.loc['Albania']

Rank                                 138
CCA3                                 ALB
Capital                           Tirana
Continent                         Europe
2022 Population                2842321.0
2020 Population                2866849.0
2015 Population                2882481.0
2010 Population                2913399.0
2000 Population                3182021.0
1990 Population                3295066.0
1980 Population                2941651.0
1970 Population                2324731.0
Area (km²)                       28748.0
Density (per km²)                98.8702
Growth Rate                       0.9957
World Population Percentage         0.04
Name: Albania, dtype: object

In [7]:
df.loc['Albania', ['2022 Population', "Area (km²)"]]

2022 Population    2842321.0
Area (km²)           28748.0
Name: Albania, dtype: object

In [107]:
df2 = df.loc[['Albania', 'Bulgaria'], ['2022 Population', "Area (km²)"]]
df2

          2022 Population  Area (km²)
Country
Albania         2842321.0     28748.0
Bulgaria        6781953.0    110879.0

In [108]:
df2 = df.loc[:, ['2022 Population', "Area (km²)"]]
df2

                                  2022 Population  Area (km²)
Country
Afghanistan                          4.112877e+07    652230.0
Albania                              2.842321e+06     28748.0
Algeria                              4.490322e+07   2381741.0
American Samoa                       4.427300e+04       199.0
Andorra                              7.982400e+04       468.0
Angola                               3.558899e+07   1246700.0
Anguilla                             1.585700e+04        91.0
Antigua and Barbuda                  9.376300e+04       442.0
Argentina                            4.551032e+07   2780400.0
Armenia                              2.780469e+06     29743.0
Aruba                                1.064450e+05       180.0
Australia                            2.617741e+07   7692024.0
Austria                              8.939617e+06     83871.0
Azerbaijan                           1.035807e+07     86600.0
Bahamas                              4.099840e+05     13943.0
Bahrain                              1.472233e+06       765.0
Bangladesh                           1.711864e+08    147570.0
Barbados                             2.816350e+05       430.0
Belarus                              9.534954e+06    207600.0
Belgium                              1.165593e+07     30528.0
Belize                               4.052720e+05     22966.0
Benin                                1.335286e+07    112622.0
Bermuda                              6.418400e+04        54.0
Bhutan                               7.824550e+05     38394.0
Bolivia                              1.222411e+07   1098581.0
Bosnia and Herzegovina               3.233526e+06     51209.0
Botswana                             2.630296e+06    582000.0
Brazil                               2.153135e+08   8515767.0
British Virgin Islands               3.130500e+04       151.0
Brunei                               4.490020e+05      5765.0
Bulgaria                             6.781953e+06    110879.0
Burkina Faso                         2.267376e+07    272967.0
Burundi                              1.288958e+07     27834.0
Cambodia                             1.676784e+07    181035.0
Cameroon                             2.791454e+07    475442.0
Canada                               3.845433e+07   9984670.0
Cape Verde                           5.931490e+05      4033.0
Cayman Islands                       6.870600e+04       264.0
Central African Republic             5.579144e+06    622984.0
Chad                                 1.772332e+07   1284000.0
Chile                                1.960373e+07    756102.0
China                                1.425887e+09   9706961.0
Colombia                             5.187402e+07   1141748.0
Comoros                              8.367740e+05      1862.0
Cook Islands                         1.701100e+04       236.0
Costa Rica                           5.180829e+06     51100.0
Croatia                              4.030358e+06     56594.0
Cuba                                 1.121219e+07    109884.0
Curacao                              1.911630e+05       444.0
Cyprus                               1.251488e+06      9251.0
Czech Republic                       1.049399e+07     78865.0
Denmark                              5.882261e+06     43094.0
Djibouti                             1.120849e+06     23200.0
Dominica                             7.273700e+04       751.0
Dominican Republic                   1.122882e+07     48671.0
DR Congo                             9.901021e+07   2344858.0
Ecuador                              1.800100e+07    276841.0
Egypt                                1.109901e+08   1002450.0
El Salvador                          6.336392e+06     21041.0
Equatorial Guinea                    1.674908e+06     28051.0
Eritrea                              3.684032e+06    117600.0
Estonia                              1.326062e+06     45227.0
Eswatini                                      NaN     17364.0
Ethiopia                             1.233799e+08   1104300.0
Falkland Islands                     3.780000e+03     12173.0
Faroe Islands                        5.309000e+04      1393.0
Fiji                                 9.297660e+05     18272.0
Finland                              5.540745e+06    338424.0
France                               6.462663e+07    551695.0
French Guiana                        3.045570e+05     83534.0
French Polynesia                     3.062790e+05      4167.0
Gabon                                2.388992e+06    267668.0
Gambia                               2.705992e+06     10689.0
Georgia                              3.744385e+06     69700.0
Germany                              8.336984e+07    357114.0
Ghana                                3.347587e+07    238533.0
Gibraltar                            3.264900e+04         6.0
Greece                               1.038497e+07    131990.0
Greenland                            5.646600e+04   2166086.0
Grenada                              1.254380e+05       344.0
Guadeloupe                           3.957520e+05      1628.0
Guam                                 1.717740e+05       549.0
Guatemala                            1.784391e+07    108889.0
Guernsey                             6.330100e+04        78.0
Guinea                               1.385934e+07    245857.0
Guinea-Bissau                        2.105566e+06     36125.0
Guyana                               8.087260e+05    214969.0
Haiti                                1.158500e+07     27750.0
Honduras                             1.043286e+07    112492.0
Hong Kong                            7.488865e+06      1104.0
Hungary                              9.967308e+06     93028.0
Iceland                              3.728990e+05    103000.0
India                                1.417173e+09   3287590.0
Indonesia                            2.755013e+08   1904569.0
Iran                                 8.855057e+07   1648195.0
Iraq                                 4.449612e+07    438317.0
Ireland                              5.023109e+06     70273.0
Isle of Man                          8.451900e+04       572.0
Israel                               9.038309e+06     20770.0
Italy                                5.903747e+07    301336.0
Ivory Coast                          2.816054e+07    322463.0
Jamaica                              2.827377e+06     10991.0
Japan                                1.239517e+08    377930.0
Jersey                               1.107780e+05       116.0
Jordan                               1.128587e+07     89342.0
Kazakhstan                           1.939800e+07   2724900.0
Kenya                                5.402749e+07    580367.0
Kiribati                             1.312320e+05       811.0
Kuwait                               4.268873e+06     17818.0
Kyrgyzstan                           6.630623e+06    199951.0
Laos                                 7.529475e+06    236800.0
Latvia                               1.850651e+06     64559.0
Lebanon                              5.489739e+06     10452.0
Lesotho                              2.305825e+06     30355.0
Liberia                              5.302681e+06    111369.0
Libya                                6.812341e+06   1759540.0
Liechtenstein                        3.932700e+04       160.0
Lithuania                            2.750055e+06     65300.0
Luxembourg                           6.475990e+05      2586.0
Macau                                6.951680e+05        30.0
Madagascar                           2.961171e+07    587041.0
Malawi                               2.040532e+07    118484.0
Malaysia                             3.393822e+07    330803.0
Maldives                             5.237870e+05       300.0
Mali                                 2.259359e+07   1240192.0
Malta                                5.332860e+05       316.0
Marshall Islands                     4.156900e+04       181.0
Martinique                           3.675070e+05      1128.0
Mauritania                           4.736139e+06   1030700.0
Mauritius                            1.299469e+06      2040.0
Mayotte                              3.261010e+05       374.0
Mexico                               1.275041e+08   1964375.0
Micronesia                           1.141640e+05       702.0
Moldova                              3.272996e+06     33846.0
Monaco                               3.646900e+04         2.0
Mongolia                             3.398366e+06   1564110.0
Montenegro                           6.270820e+05     13812.0
Montserrat                           4.390000e+03       102.0
Morocco                              3.745797e+07    446550.0
Mozambique                           3.296952e+07    801590.0
Myanmar                              5.417931e+07    676578.0
Namibia                              2.567012e+06    825615.0
Nauru                                1.266800e+04        21.0
Nepal                                3.054758e+07    147181.0
Netherlands                          1.756401e+07     41850.0
New Caledonia                        2.899500e+05     18575.0
New Zealand                          5.185288e+06    270467.0
Nicaragua                            6.948392e+06    130373.0
Niger                                2.620798e+07   1267000.0
Nigeria                              2.185412e+08    923768.0
Niue                                 1.934000e+03       260.0
North Korea                          2.606942e+07    120538.0
North Macedonia                      2.093599e+06     25713.0
Northern Mariana Islands             4.955100e+04       464.0
Norway                                        NaN    323802.0
Oman                                 4.576298e+06    309500.0
Pakistan                             2.358249e+08    881912.0
Palau                                         NaN       459.0
Palestine                            5.250072e+06      6220.0
Panama                               4.408581e+06     75417.0
Papua New Guinea                     1.014262e+07    462840.0
Paraguay                             6.780744e+06    406752.0
Peru                                 3.404959e+07   1285216.0
Philippines                          1.155590e+08    342353.0
Poland                               3.985714e+07    312679.0
Portugal                             1.027086e+07     92090.0
Puerto Rico                          3.252407e+06      8870.0
Qatar                                2.695122e+06     11586.0
Republic of the Congo                5.970424e+06    342000.0
Reunion                              9.740520e+05      2511.0
Romania                              1.965927e+07    238391.0
Russia                               1.447133e+08  17098242.0
Rwanda                               1.377670e+07     26338.0
Saint Barthelemy                     1.096700e+04        21.0
Saint Kitts and Nevis                4.765700e+04       261.0
Saint Lucia                          1.798570e+05       616.0
Saint Martin                         3.179100e+04        53.0
Saint Pierre and Miquelon            5.862000e+03       242.0
Saint Vincent and the Grenadines     1.039480e+05       389.0
Samoa                                2.223820e+05      2842.0
San Marino                           3.366000e+04        61.0
Sao Tome and Principe                2.273800e+05       964.0
Saudi Arabia                         3.640882e+07   2149690.0
Senegal                              1.731645e+07         NaN
Serbia                               7.221365e+06     88361.0
Seychelles                           1.071180e+05       452.0
Sierra Leone                         8.605718e+06     71740.0
Singapore                            5.975689e+06       710.0
Sint Maarten                         4.417500e+04        34.0
Slovakia                             5.643453e+06     49037.0
Slovenia                             2.119844e+06     20273.0
Solomon Islands                      7.242730e+05     28896.0
Somalia                              1.759751e+07    637657.0
South Africa                         5.989388e+07   1221037.0
South Korea                          5.181581e+07    100210.0
South Sudan                          1.091316e+07    619745.0
Spain                                4.755863e+07    505992.0
Sri Lanka                            2.183214e+07     65610.0
Sudan                                4.687420e+07   1886068.0
Suriname                             6.180400e+05    163820.0
Sweden                               1.054935e+07    450295.0
Switzerland                          8.740472e+06     41284.0
Syria                                2.212525e+07    185180.0
Taiwan                               2.389339e+07     36193.0
Tajikistan                           9.952787e+06    143100.0
Tanzania                             6.549775e+07    945087.0
Thailand                             7.169703e+07    513120.0
Timor-Leste                                   NaN     14874.0
Togo                                 8.848699e+06     56785.0
Tokelau                              1.871000e+03        12.0
Tonga                                1.068580e+05       747.0
Trinidad and Tobago                  1.531044e+06      5130.0
Tunisia                              1.235612e+07    163610.0
Turkey                               8.534124e+07    783562.0
Turkmenistan                         6.430770e+06    488100.0
Turks and Caicos Islands             4.570300e+04       948.0
Tuvalu                               1.131200e+04        26.0
Uganda                               4.724958e+07    241550.0
Ukraine                              3.970174e+07    603500.0
United Arab Emirates                 9.441129e+06     83600.0
United Kingdom                       6.750894e+07    242900.0
United States                        3.382899e+08   9372610.0
United States Virgin Islands         9.946500e+04       347.0
Uruguay                              3.422794e+06    181034.0
Uzbekistan                           3.462765e+07    447400.0
Vanuatu                              3.267400e+05     12189.0
Vatican City                         5.100000e+02         1.0
Venezuela                            2.830170e+07         NaN
Vietnam                              9.818686e+07    331212.0
Wallis and Futuna                    1.157200e+04       142.0
Western Sahara                       5.759860e+05    266000.0
Yemen                                3.369661e+07    527968.0
Zambia                               2.001768e+07    752612.0
Zimbabwe                             1.632054e+07    390757.0

In [109]:
df.iloc[0:11, [2,3,5]]

                              Capital      Continent  2020 Population
Country
Afghanistan                     Kabul           Asia       38972230.0
Albania                        Tirana         Europe        2866849.0
Algeria                       Algiers         Africa       43451666.0
American Samoa              Pago Pago        Oceania          46189.0
Andorra              Andorra la Vella         Europe          77700.0
Angola                         Luanda         Africa       33428485.0
Anguilla                   The Valley  North America          15585.0
Antigua and Barbuda      Saint John’s  North America          92664.0
Argentina                Buenos Aires  South America       45036032.0
Armenia                       Yerevan           Asia        2805608.0
Aruba                      Oranjestad  North America         106585.0

## Multiple Index

Сброс индекса

In [110]:
df.head()

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00

In [111]:
df.reset_index(inplace=True)
df.head()

,Country,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00

In [112]:
df.set_index(["Continent","Country"], inplace=True)

In [116]:
df.sort_index(inplace=True)
pd.set_option("display.max.rows", 100)
df[100:125]

                                  Rank CCA3           Capital  \
Continent Country
Asia      Timor-Leste              155  TLS              Dili
          Turkey                    18  TUR            Ankara
          Turkmenistan             111  TKM          Ashgabat
          United Arab Emirates      97  ARE         Abu Dhabi
          Uzbekistan                43  UZB          Tashkent
          Vietnam                   16  VNM             Hanoi
          Yemen                     46  YEM             Sanaa
Europe    Albania                  138  ALB            Tirana
          Andorra                  203  AND  Andorra la Vella
          Austria                   99  AUT            Vienna
          Belarus                   96  BLR             Minsk
          Belgium                   81  BEL          Brussels
          Bosnia and Herzegovina   137  BIH          Sarajevo
          Bulgaria                 108  BGR             Sofia
          Croatia                  130  HRV            Zagreb
          Cyprus                   158  CYP           Nicosia
          Czech Republic            88  CZE            Prague
          Denmark                  115  DNK        Copenhagen
          Estonia                  156  EST           Tallinn
          Faroe Islands            209  FRO          Tórshavn
          Finland                  118  FIN          Helsinki
          France                    23  FRA             Paris
          Germany                   19  DEU            Berlin
          Gibraltar                219  GIB         Gibraltar
          Greece                    90  GRC            Athens

                                  2022 Population  2020 Population  \
Continent Country
Asia      Timor-Leste                         NaN        1299995.0
          Turkey                       85341241.0       84135428.0
          Turkmenistan                  6430770.0        6250438.0
          United Arab Emirates          9441129.0        9287289.0
          Uzbekistan                   34627652.0       33526656.0
          Vietnam                      98186856.0       96648685.0
          Yemen                        33696614.0       32284046.0
Europe    Albania                       2842321.0        2866849.0
          Andorra                         79824.0          77700.0
          Austria                       8939617.0        8907777.0
          Belarus                       9534954.0        9633740.0
          Belgium                      11655930.0       11561717.0
          Bosnia and Herzegovina        3233526.0        3318407.0
          Bulgaria                      6781953.0        6979175.0
          Croatia                       4030358.0        4096868.0
          Cyprus                        1251488.0        1237537.0
          Czech Republic               10493986.0       10530953.0
          Denmark                       5882261.0        5825641.0
          Estonia                       1326062.0        1329444.0
          Faroe Islands                   53090.0          52415.0
          Finland                       5540745.0        5529468.0
          France                       64626628.0       64480053.0
          Germany                      83369843.0       83328988.0
          Gibraltar                       32649.0          32709.0
          Greece                       10384971.0       10512232.0

                                  2015 Population  2010 Population  \
Continent Country
Asia      Timor-Leste                   1205813.0        1088486.0
          Turkey                       79646178.0       73195345.0
          Turkmenistan                  5766431.0        5267970.0
          United Arab Emirates          8916899.0        8481771.0
          Uzbekistan                   30949417.0       28614227.0
          Vietnam                      92191398.0       87411012.0
          Yemen                        28516545.0       24743946.0
Europe    Albania                       2882481.0        2913399.0
          Andorra                         71746.0          71519.0
          Austria                       8642421.0        8362829.0
          Belarus                       9700609.0        9731427.0
          Belgium                      11248303.0       10877947.0
          Bosnia and Herzegovina        3524324.0        3811088.0
          Bulgaria                      7309253.0        7592273.0
          Croatia                       4254815.0        4368682.0
          Cyprus                        1187280.0        1129686.0
          Czech Republic               10523798.0       10464749.0
          Denmark                       5677796.0        5550849.0
          Estonia                       1314657.0        1331535.0
          Faroe Islands                   48816.0          48410.0
          Finland                       5479461.0        5363271.0
          France                       63809769.0       62444567.0
          Germany                      82073226.0       81325090.0
          Gibraltar                       32520.0          31262.0
          Greece                       10806641.0       11033783.0

                                  2000 Population  1990 Population  \
Continent Country
Asia      Timor-Leste                         NaN         758106.0
          Turkey                       64113547.0       54324142.0
          Turkmenistan                  4569132.0        3720278.0
          United Arab Emirates          3275333.0        1900151.0
          Uzbekistan                   24925554.0       20579100.0
          Vietnam                      79001142.0       66912613.0
          Yemen                        18628700.0       13375121.0
Europe    Albania                       3182021.0        3295066.0
          Andorra                         66097.0          53569.0
          Austria                       8010428.0        7678729.0
          Belarus                      10256483.0       10428525.0
          Belgium                      10264343.0        9959560.0
          Bosnia and Herzegovina        4179350.0        4494310.0
          Bulgaria                      8097691.0        8767778.0
          Croatia                       4548434.0        4873707.0
          Cyprus                         948237.0         788500.0
          Czech Republic               10234710.0       10301192.0
          Denmark                       5340655.0        5144623.0
          Estonia                       1396877.0        1570674.0
          Faroe Islands                   45660.0          47479.0
          Finland                       5176209.0        4986545.0
          France                       58665453.0       56412897.0
          Germany                      81551677.0       79370196.0
          Gibraltar                       27741.0          27317.0
          Greece                       11038109.0       10302255.0

                                  1980 Population  1970 Population  \
Continent Country
Asia      Timor-Leste                    642224.0         554021.0
          Turkey                       44089069.0       35540990.0
          Turkmenistan                  2862903.0        2201432.0
          United Arab Emirates          1014048.0         298084.0
          Uzbekistan                   15947129.0       12011361.0
          Vietnam                      52968270.0       41928849.0
          Yemen                         9204938.0        6843607.0
Europe    Albania                       2941651.0        2324731.0
          Andorra                         35611.0          19860.0
          Austria                       7547561.0        7465301.0
          Belarus                       9817257.0        9170786.0
          Belgium                       9828986.0        9629376.0
          Bosnia and Herzegovina        4199820.0        3815561.0
          Bulgaria                      8980606.0        8582950.0
          Croatia                       4680144.0        4492638.0
          Cyprus                         679327.0         640804.0
          Czech Republic               10270060.0        9795744.0
          Denmark                       5125392.0        4922963.0
          Estonia                       1476983.0        1361999.0
          Faroe Islands                   43054.0          38416.0
          Finland                       4779418.0        4606621.0
          France                       53713830.0       50523586.0
          Germany                      77786703.0       78294583.0
          Gibraltar                       28734.0          26685.0
          Greece                        9307148.0        8544873.0

                                  Area (km²)  Density (per km²)  Growth Rate  \
Continent Country
Asia      Timor-Leste                14874.0            90.1772       1.0154
          Turkey                    783562.0           108.9145       1.0067
          Turkmenistan              488100.0            13.1751       1.0140
          United Arab Emirates       83600.0           112.9322       1.0081
          Uzbekistan                447400.0            77.3975       1.0160
          Vietnam                   331212.0           296.4472       1.0074
          Yemen                     527968.0            63.8232       1.0217
Europe    Albania                    28748.0            98.8702       0.9957
          Andorra                      468.0           170.5641       1.0100
          Austria                    83871.0           106.5877       1.0020
          Belarus                   207600.0            45.9295       0.9955
          Belgium                    30528.0           381.8111       1.0038
          Bosnia and Herzegovina     51209.0            63.1437       0.9886
          Bulgaria                  110879.0            61.1654       0.9849
          Croatia                    56594.0            71.2153       0.9927
          Cyprus                      9251.0           135.2814       1.0059
          Czech Republic             78865.0           133.0627       0.9984
          Denmark                    43094.0           136.4984       1.0048
          Estonia                    45227.0            29.3201       0.9980
          Faroe Islands               1393.0            38.1120       1.0038
          Finland                   338424.0            16.3722       1.0009
          France                    551695.0           117.1419       1.0015
          Germany                   357114.0           233.4544       0.9995
          Gibraltar                      6.0          5441.5000       0.9994
          Greece                    131990.0            78.6800       0.9942

                                  World Population Percentage
Continent Country
Asia      Timor-Leste                                    0.02
          Turkey                                         1.07
          Turkmenistan                                   0.08
          United Arab Emirates                           0.12
          Uzbekistan                                     0.43
          Vietnam                                        1.23
          Yemen                                          0.42
Europe    Albania                                        0.04
          Andorra                                        0.00
          Austria                                        0.11
          Belarus                                        0.12
          Belgium                                        0.15
          Bosnia and Herzegovina                         0.04
          Bulgaria                                       0.09
          Croatia                                        0.05
          Cyprus                                         0.02
          Czech Republic                                 0.13
          Denmark                                        0.07
          Estonia                                        0.02
          Faroe Islands                                  0.00
          Finland                                        0.07
          France                                         0.81
          Germany                                        1.05
          Gibraltar                                      0.00
          Greece                                         0.13

In [117]:
df

                            Rank CCA3      Capital  2022 Population  \
Continent     Country
Africa        Algeria         34  DZA      Algiers       44903225.0
              Angola          42  AGO       Luanda       35588987.0
              Benin           77  BEN   Porto-Novo       13352864.0
              Botswana       144  BWA     Gaborone        2630296.0
              Burkina Faso    58  BFA  Ouagadougou       22673762.0
...                          ...  ...          ...              ...
South America Paraguay       109  PRY     Asunción        6780744.0
              Peru            44  PER         Lima       34049588.0
              Suriname       170  SUR   Paramaribo         618040.0
              Uruguay        133  URY   Montevideo        3422794.0
              Venezuela       51  VEN      Caracas       28301696.0

                            2020 Population  2015 Population  2010 Population  \
Continent     Country
Africa        Algeria            43451666.0       39543154.0       35856344.0
              Angola             33428485.0       28127721.0       23364185.0
              Benin              12643123.0       10932783.0        9445710.0
              Botswana            2546402.0        2305171.0        2091664.0
              Burkina Faso       21522626.0       18718019.0       16116845.0
...                                     ...              ...              ...
South America Paraguay            6618695.0        6177950.0        5768613.0
              Peru               33304756.0       30711863.0       29229572.0
              Suriname             607065.0         575475.0         546080.0
              Uruguay             3429086.0        3402818.0        3352651.0
              Venezuela          28490453.0       30529716.0       28715022.0

                            2000 Population  1990 Population  1980 Population  \
Continent     Country
Africa        Algeria            30774621.0       25518074.0       18739378.0
              Angola             16394062.0       11828638.0        8330047.0
              Benin               6998023.0        5133419.0        3833939.0
              Botswana            1726985.0        1341474.0         938578.0
              Burkina Faso       11882888.0        9131361.0        6932967.0
...                                     ...              ...              ...
South America Paraguay            5123819.0        4059195.0        3078912.0
              Peru               26654439.0       22109099.0       17492406.0
              Suriname             478998.0         412756.0         375112.0
              Uruguay             3292224.0        3117012.0        2953750.0
              Venezuela                 NaN       19750579.0       15210443.0

                            1970 Population  Area (km²)  Density (per km²)  \
Continent     Country
Africa        Algeria            13795915.0   2381741.0            18.8531
              Angola              6029700.0   1246700.0            28.5466
              Benin               3023443.0    112622.0           118.5635
              Botswana             592244.0    582000.0             4.5194
              Burkina Faso        5611666.0    272967.0            83.0641
...                                     ...         ...                ...
South America Paraguay            2408787.0    406752.0            16.6705
              Peru               13562371.0   1285216.0            26.4933
              Suriname             379918.0    163820.0             3.7727
              Uruguay             2790265.0    181034.0            18.9069
              Venezuela          11355475.0         NaN            30.8820

                            Growth Rate  World Population Percentage
Continent     Country
Africa        Algeria            1.0164                         0.56
              Angola             1.0315                         0.45
              Benin              1.0274                         0.17
              Botswana           1.0162                         0.03
              Burkina Faso       1.0259                         0.28
...                                 ...                          ...
South America Paraguay           1.0115                         0.09
              Peru               1.0099                         0.43
              Suriname           1.0082                         0.01
              Uruguay            0.9990                         0.04
              Venezuela          1.0036                         0.35

[234 rows x 15 columns]

In [120]:
df.loc['Asia', 'Bahrain']

Rank                                 154
CCA3                                 BHR
Capital                           Manama
2022 Population                1472233.0
2020 Population                1477469.0
2015 Population                1362142.0
2010 Population                1213645.0
2000 Population                 711442.0
1990 Population                 517418.0
1980 Population                 362595.0
1970 Population                 222555.0
Area (km²)                         765.0
Density (per km²)              1924.4876
Growth Rate                       1.0061
World Population Percentage         0.02
Name: (Asia, Bahrain), dtype: object